In [27]:
import pandas as pd
import numpy as np

In [28]:
df=pd.read_csv("/Users/user/Desktop/Machine_learning _zoocamp _001/car_fuel_efficiency_csv.csv")

In [29]:
df.head(10)

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
5,190,3.0,NaN,2484.883986,14.7,2008,Europe,Gasoline,All-wheel drive,-1.0,17.271818
6,240,7.0,127.0,3006.542287,22.2,2012,USA,Gasoline,Front-wheel drive,1.0,13.210412
7,150,4.0,239.0,3638.657780,17.3,2020,USA,Diesel,All-wheel drive,1.0,12.848884
8,250,1.0,174.0,2714.219310,10.3,2016,Asia,Diesel,Front-wheel drive,-1.0,16.823554
9,150,4.0,123.0,3509.036569,10.2,2005,USA,Gasoline,Front-wheel drive,-1.0,12.298355

In [30]:
df.shape

(9704, 11)

In [31]:
df.fuel_type.unique()

array(['Gasoline', 'Diesel'], dtype=object)

In [32]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [33]:
df.describe()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,num_doors,fuel_efficiency_mpg
count,9704.000000,9222.000000,8996.000000,9704.000000,8774.000000,9704.000000,9202.000000,9704.000000
mean,199.708368,3.962481,149.657292,3001.280993,15.021928,2011.484027,-0.006412,14.985243
std,49.455319,1.999323,29.879555,497.894860,2.510339,6.659808,1.048162,2.556468
min,10.000000,0.000000,37.000000,952.681761,6.000000,2000.000000,-4.000000,6.200971
25%,170.000000,3.000000,130.000000,2666.248985,13.300000,2006.000000,-1.000000,13.267459
50%,200.000000,4.000000,149.000000,2993.226296,15.000000,2012.000000,0.000000,15.006037
75%,230.000000,5.000000,170.000000,3334.957039,16.700000,2017.000000,1.000000,16.707965
max,380.000000,13.000000,271.000000,4739.077089,24.300000,2023.000000,4.000000,25.967222

In [35]:
df[df["origin"] == "Asia"]["fuel_efficiency_mpg"].max()

23.75912284

In [ ]:
df["horsepower"].median()

149.0

In [37]:
df["horsepower"].mode()

0    152.0
Name: horsepower, dtype: float64

In [41]:
median_before = df["horsepower"].median()

# Find the most frequent value (mode) of horsepower
most_frequent = df["horsepower"].mode()[0]

# Fill missing values in horsepower with the most frequent value
df["horsepower"].fillna(most_frequent, inplace=True)

# Find the median value of horsepower after filling missing values
median_after = df["horsepower"].median()

In [42]:
df["horsepower"].median()

152.0

In [ ]:
df["vehicle_weight"].sum()

29124430.759705596

In [43]:
X = df[df["origin"] == "Asia"][["vehicle_weight", "model_year"]].head(7).values

# Matrix-matrix multiplication
XTX = X.T @ X

# Invert XTX
XTX_inv = np.linalg.inv(XTX)

# Create y array
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Compute w
w = XTX_inv @ X.T @ y

# Sum of all elements in w
result_sum = w.sum()
result_sum

0.5187709081604045